import type { Metadata } from "next";
import { LingoProvider } from "@lingo.dev/compiler/react";
import "./globals.css";
import HTMLWrapper from "@/components/HTMLWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <LingoProvider>
      <HTMLWrapper>{children}</HTMLWrapper>
    </LingoProvider>
  );
}
